name: PvPTeleport
main: net.simpvp.PvPTeleport.PvPTeleport
version: 1.8
api-version: 1.13
commands:
  world:
    description: Teleports player between overworld and small world.
    usage: Error. Please report at https://github.com/C4K3/PvPTeleport
  smlist:
    description: Lists all players in the small world.
    usage: Error. Please report at https://github.com/C4K3/PvPTeleport
  disableworld:
    description: Disables the /world command, returns everybody back to the overworld.
